name: Simple CI

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run hello_world.sh
      run: ./hello_world.sh
